### ISSUE TITLE
Feature Request: Code comments

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#102]
**User Story**
As a developer,
I want to add comments to my code,
So other developers can understand it

**Priority**
[x]: High
[]: Medium
[]: Low

**Describe the solution you want to implement**
Please add appropriate comments to code you have contributed.

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
n/a

**Comment by SeanSpires** [comment]
I believe that the back-end was commented as it was being developed. I've just had another look at it seems fine. @lken274 can you confirm?

**Comment by williamlixu** [comment]
I think the front-end code is pretty simple and self-documenting in general. Comments have been used tastefully and the code makes sense through our rigorous code review process. I'm happy for this issue to be closed if you guys think the commenting and docs are up to scratch!

**Comment by dder725** [comment]
In light of the previous comments, this issue is closed :)
