### ISSUE TITLE
Document deployment

### ISSUE THREAD

**Issue by margeobur** [se701-group6/A2#120]
**Is your feature request related to a problem? Please describe.**
This documentation will be related to issue #111 

**Describe the type of Document Change you'd like to be added**
Mark with an x
- [x] Addition
- [ ] Edit
- [ ] Remove

**Describe the change you would like to be made**
I would like to describe the way deployment has been configured so that people can understand how it works and so the next team can make use of it.

**Comment by williamlixu** [comment]
~~Closed as duplicate of #121~~ 
Closed #121 instead

**Comment by margeobur** [comment]
[Completed wiki page](https://github.com/SOFTENG701G1/A1/wiki/CI-CD#deployment)

**Comment by williamlixu** [comment]
Great work! Write up is really clear and the diagrams are neat. Hopefully the docs help the next group pick up the project. Closing issue now.
