### ISSUE TITLE
Encrypt passwords

### ISSUE THREAD

**Issue by williamlixu** [se701-group6/A2#124]
**User Story**
As a user
I want my password to be stored in a secure fashion
So that my password is kept secret from other people and won't get hacked easily

**Priority**
- [x] High
- [ ] Medium
- [ ] Low

**Describe the solution you want to implement**
* Hash passwords on the sign up form in web-app before sending to the back-end
* Hash password on login and verify it makes the stored password (which should be hashed).
* Backend should only store hashed passwords 
* Document the new API changes if needed

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
Currently passwords are stored and used in plaintext.

**Comment by ErnWong** [comment]
Hash algorithm: sha256?

**Comment by timovv** [comment]
It's probably best to use a slow hashing algorithm like pbkdf2, scrypt, etc. My understanding is that plain SHA-2 is thought to be too fast these days for use in hashing passwords. `hashlib` from the Python standard library has support for a wide array of different hash algorithms so there shouldn't be any issues on the backend.

Also, hashing should exclusively occur on the server side, as opposed to the client-side solution proposed. Hashing on the client side is insecure, as it allows for the following attack vector:
1. Attacker gains access to database with password hashes
2. Attacker sends an API request to sign in using the password hash
3. Attacker is now in control of account
