### ISSUE TITLE
Feature request: Set up a blank React project

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#13]
As a developer,
I want to set up a blank React project
So others can work on it

**Priority**
High

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
A blank React project is served when accessing 127.0.0.1:1234.

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
No

**Additional context**
n/a

**Comment by pabloSushibar** [comment]
PR #17 closes this issue. I miss typed the issue number during the commit. Sorry about it.
