### ISSUE TITLE
Split css into multiple files

### ISSUE THREAD

**Issue by FrankWangma** [se701-group6/A2#136]
**User Story**
As a developer
I want to have the css in different files
So that it is easier to see which css corresponds to which page

**Priority**
- [ ] High
- [x] Medium
- [ ] Low

**Describe the solution you want to implement**
Split the css file into multiple files that correspond to each page

* Should be done as you go (i.e. If you run into a component that retreives css from App.css, refactor it into a module.css file inside the same folder as the component. Best practice is to move the component and the module.css file into its own sub folder.)

**Describe alternatives you've considered**
N/A

**Issue Dependencies**
N/A

**Additional context**
N/A

**Comment by ErnWong** [comment]
Thoughts on using Material-UI's style solution instead of module css? Allows using material-ui's theming framework, and probably works well with material ui component styles. https://material-ui.com/styles/basics/

**Comment by ErnWong** [comment]
^ We decided to just use module css files. Easier and solves what we need.
