### ISSUE TITLE
Removing people from a split bill during creation

### ISSUE THREAD

**Issue by kaplunket** [se701-group6/A2#138]
**Describe the bug**
When making a bill to split, if I accidentally add an extra person I cant remove them

**To Reproduce**
1. Make a new bill
2. Add two people
3. Try to remove one, and be unable to

**Severity**
Mark with an x.
[x]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
I'd like to be able to remove people, perhaps with a little x

**Conditions**
List the setup you used to create this bug, eg OS, hardware, browser
Firefox, Ubuntu

**Comment by ErnWong** [comment]
Blocked by #129

**Comment by ErnWong** [comment]
Done via #129
