### ISSUE TITLE
Feature request: App design

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#14]
As a front-end developer
I want to have a mockup of the app
So I can build it

**Priority**
High   

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
A clean concise mockup of all necessary screens of the app with any necessary notes for devs. The screens can be found [here](https://github.com/SOFTENG701G1/A1/wiki/Mockups).

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
It has been decided to use [material library](https://material-ui.com/) for SPLiT UI, so the design should take this into account.

**Comment by pabloSushibar** [comment]
I accidentally had a typo, was meant to close issue #13 but I closed issue #14. Sorry about it.

**Comment by SeanSpires** [comment]
I believe this issue is now resolved. Closing now, if anyone has an issue with this reopen the issue and leave a comment.
