### ISSUE TITLE
Sign out button does not remove credentials

### ISSUE THREAD

**Issue by kaplunket** [se701-group6/A2#142]
**Describe the bug**
If a user is logged in and then clicks the sign out button they are redirected to the sign in page.
However, if the user hits the back button or enters the link for the transaction page they will still be logged in.

**To Reproduce**
1. Login
2. Log out
3. Hit the back button, or go to any other page.
4. You will be logged in as the last user

**Severity**
Mark with an x.
[]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[x]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
The user should not be logged in, as the user has opted to log out. Credentials should be thrown away.

**Conditions**
List the setup you used to create this bug, eg OS, hardware, browser
Ubuntu, Firefox

**Additional context**
Session data seems to be stored in the back end, an API call may be necessary to let the back end know to throw away the session data.

**Comment by ErnWong** [comment]
Hey @kaplunket, just wondering, what does the 'invalid' label mean in this case?

**Comment by kaplunket** [comment]
> Hey @kaplunket, just wondering, what does the 'invalid' label mean in this case?

I wasn't sure if it referred to the issue or the bug but I added it just in case. It was an existing label that just says this doesn't seem right. In the way that I intend it, this behaviour doesn't seem right.
