### ISSUE TITLE
Documentation request: API documentation

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#16]
**Is your feature request related to a problem? Please describe.**
We need documentation for the API so that the front-end team knows what endpoints to call.

**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
A clear and concise description of API endpoints alongside the payloads that the API receives/sends back.

**Issue Dependencies**
None

**Additional context**
-

**Comment by lken274** [comment]
https://github.com/SOFTENG701G1/A1/wiki/API-Description

Here's a rough initial draft. Please review and add suggestions. Will need back-end and front-end contributions (and possibly formatting from the docs team)

**Comment by SeanSpires** [comment]
The API documentation you wrote looks clear and concise from a back-end perspective. I'll assign this task to Riley and Daria as well so we can ensure the document works for the front-end team as well as the formatting team.

**Comment by rfro377** [comment]
Looks good to me, I will wait for a reply from Daria and the front-end team on the issue. If all is good I will add the page to the wiki
Cheers
