### ISSUE TITLE
Checklist displays all contributors in a single row

### ISSUE THREAD

**Issue by michellemtan** [se701-group6/A2#160]
**Describe the bug**
The contributors pending and paid are being merged into a single checklist

**To Reproduce**
1. Go to payments
2. Click on new payment
3. Scroll down to contributors pending/paid

**Severity**
Mark with an x.
[]: Minor effect eg. graphical
[X]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[X]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
The contributors pending and paid should be displayed in separate rows with checkboxes

**Screenshots, Images and Traces**
If applicable, add screenshots, images or stack Traces to help explain your problem.

**Conditions**
Google Chrome

**Issue Dependencies**
No

**Additional context**

**Comment by kaplunket** [comment]
Hi, can you confirm this is a bug for Split?

**Comment by tyger-kong** [comment]
> Hi, can you confirm this is a bug for Split?

No, there has been a mistake. The creator of this issue was working on this project for A1. She must've gotten the repo's mixed up.

**Comment by tyger-kong** [comment]
Closing issue
