### ISSUE TITLE
Documentation Request: Database documentation

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#21]
**Is your feature request related to a problem? Please describe.**
We need database documentation so we can keep track of all aspects of the database.

**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
A brief overview of what type of database we're using alongside details on what type of data structure is used within the database.

**Issue Dependencies**
#18 

**Additional context**
n/a

**Comment by lken274** [comment]
https://github.com/SOFTENG701G1/A1/wiki/Database-Structure

Please check above and add link to the wiki home page if acceptable

**Comment by SeanSpires** [comment]
Looks good, great work Logan. Adding to the doc to the home page and closing this issue now.
