### ISSUE TITLE
Feature request: Get specific bill

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#27]
**User Story**
For example: 
As a user
I want to be able to requests details about one of my specific bills

**Priority**
[x]: High
[]: Medium
[]: Low

**Describe the solution you want to implement**
A way for the user to request the details about on their bills

**Describe alternatives you've considered**
none so far

**Issue Dependencies**
#18 
#19 
#22 
#23 
**Additional context**
n/a

**Comment by lken274** [comment]
Due to the change in API requirements, we will always return full bill information when listing all bills. Therefore, this endpoint is no longer needed.
