### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by williamlixu** [se701-group6/A2#3]
* Probably should be a wiki page

**Comment by williamlixu** [comment]
This is pretty helpful: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by rfro377** [comment]
Issues to be approved by Sean and Daria. Assigned via a thumbs up. before being assigned

**Comment by rfro377** [comment]
Detail how to log an issue

**Comment by williamlixu** [comment]
This page should detail:
* how to raise issues and get them approved
* how the labelling system we use
* link to the wiki pages to get started / workflow
