### ISSUE TITLE
Documentation Request: App Logo

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#40]
As an app,
I want to have a logo,
So it can be used in app-related documents
**Is your feature request related to a problem? Please describe.**
No existing logo to be used in brand-related documents
**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
A logo image file is added to either the wiki or the app resources
**Issue Dependencies**
Does this issue depend on any other issues?
#14 
**Additional context**

**Comment by michellemtan** [comment]
I have added the image to the hi-fi prototypes page, here is the link if necessary: https://imgur.com/qXONyae
