### ISSUE TITLE
Documentation Request: Front-end coding standards

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#41]
**Is your feature request related to a problem? Please describe.**
Front-end devs currently have no coding standards to follow so the code is prone to be non-uniform

**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
Adding a document describing front-end coding standards

**Issue Dependencies**
n/a

**Additional context**
n/a

**Comment by skmu104** [comment]
Blank code style wiki page currently exists, Just need frontend developers subsection filled. if frontend devs can jot down some rules they follow, I can format and add to document.

**Comment by azizul-i** [comment]
I think it would be a good idea to follow AirBnb's approach to writing Javascript code as it is considered as one of the most comprehensive. I can configure the code base to have the specific rules regarding AirBnb's style of coding for our purposes (like linting, and code formatting rules), with modifications as the team deems fit. I can also add in some documentation regarding this implementation

**Comment by dder725** [comment]
@misl000 this sounds like an excellent idea! I will create an issue for linter rules to fit your proposal and close this one. Please feel free to edit the new issue (once it's up :) ) as you see fit.

**Comment by dder725** [comment]
@misl000 please see #58

**Comment by azizul-i** [comment]
The wiki has now been updated with the front-end coding standards

**Comment by williamlixu** [comment]
Looks good, closing issue now.
Coding standards can be found here: https://github.com/SOFTENG701G1/A1/wiki/Code-Style
