### ISSUE TITLE
Webapp build and test automation

### ISSUE THREAD

**Issue by margeobur** [se701-group6/A2#45]
**User Story**
For example: 
As a frontend developer
I want my PRs to be checked for build and test success
So that my reviewers and I know the code works

**Priority**
 - [ ] High
 - [x] Medium
 - [ ] Low

**Describe the solution you want to implement**
A GitHub Actions workflow that builds the frontend and runs the npm test script (which, by default, will ensure the webapp renders properly)

**Describe alternatives you've considered**
N/A

**Comment by williamlixu** [comment]
It would be nice for the CI to also check the code style using a linter, means this issue depends on #58.
