### ISSUE TITLE
Feature Request: Splitting the bill evenly

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#46]
**User Story**
As a user,
I want to be able to split the bill evenly,
So everyone pays their equal share

**Priority**
[x]: High
[]: Medium
[]: Low

**Describe the solution you want to implement**
At the transaction page, the user is able to split the bill evenly between all participants. The algorithm for this should be implemented in front-end.
When a Split button is pressed, an amount each participant owes should appear next to their name.
**Describe alternatives you've considered**
An algorithm for splitting is implemented in back end. This is however feels too complicated and unnecessary. 
**Issue Dependencies**
#33 

**Additional context**

**Comment by DevashishDhyani** [comment]
Issue dependency to #52

**Comment by dder725** [comment]
@DevashishDhyani this issue does not depend on #52. This issue is specifically for even split, no special algorithm needs to be developed for this purpose at this point.
