### ISSUE TITLE
Add brief project description to README

### ISSUE THREAD

**Issue by williamlixu** [se701-group6/A2#5]
* Include your team name 
* Include a note that this project is associated with the University of Auckland SOFTENG 701

**Comment by SeanSpires** [comment]
Could you write up a brief description of what split does, i.e. the purpose of the app, in the README Devashish? Assigned it to you as in team meetings you communicated the idea clearly and concisely.

**Comment by DevashishDhyani** [comment]
Will do tonight.

**Comment by skmu104** [comment]
I've made a template for the README.md already that's waiting to be approved in a pull request. So @DevashishDhyani can you wait for that to go through prior to updating the project description.

**Comment by DevashishDhyani** [comment]
Couldn't find the associated PR to the updated template @skmu104 , so decided to add in what @SeanSpires had asked in the README.

**Comment by DevashishDhyani** [comment]
PR #81 for the description of the web app has now been made.

**Comment by williamlixu** [comment]
Closed by #81
