### ISSUE TITLE
Feature request: Create automated testing of API endpoints

### ISSUE THREAD

**Issue by Curtiss02** [se701-group6/A2#50]
**User Story**
As a back end developer/tester
I want to create automated tests for API endpoints
So I can easily test and validate my work

**Priority**
[]: High
[✔]: Medium
[]: Low

**Describe the solution you want to implement**
Implement automated testing of API endpoints using a Postman collection run, using data files to provide different parameters to test with. Developers will run these against any changes made to server/API code to validate and test their changes.

**Describe alternatives you've considered**
N/A
**Issue Dependencies**
#42

**Additional context**
N/A

**Comment by SeanSpires** [comment]
This issue is now resolved right @Curtiss02? Since you've added the automated postman tests?

**Comment by Curtiss02** [comment]
Yeah there is always room for improvement or additional tests, but I would consider this issue closed.
