### ISSUE TITLE
Feature Request: Algorithm needed for Front-End Development and Future Work

### ISSUE THREAD

**Issue by DevashishDhyani** [se701-group6/A2#52]
**User Story**
As a developer
I want to add logic for the Splitting of Bills, so that the
Front end Developers can use it. 
Also, algorithms for future use have been added.

**Priority**
[]: Medium

**Describe the solution you want to implement**
I want to add logic for the Splitting of Bills.

**Describe alternatives you've considered**
Reaching zero transition states before we changed the front end usage.

**Issue Dependencies**
N/A

**Additional context**
N/A

**Comment by williamlixu** [comment]
Closed by wiki page here: https://github.com/SOFTENG701G1/A1/wiki/Splitting-Multiple-Bills.
