### ISSUE TITLE
Feature request: Configuring linter

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#58]
**User Story**
As a developer,
I want to be able to run linter,
So any contributed code is uniform

**Priority**
[]: High
[x]: Medium
[]: Low

**Describe the solution you want to implement**
An AirBnB eslint is configured for the application, and any code is made to comply with a standard when running `npm run lint`. A general overview of code rules enforced by a linter must be documented as per #41 

**Describe alternatives you've considered**
Standards enforced by documentation only. Hard to maintain, and ensure that they are being followed.
**Issue Dependencies**
n/a
**Additional context**
n/a

**Comment by williamlixu** [comment]
As discussed, we will try get this PR in tonight and also clean/lint all the existing front-end code so it complies.
