### ISSUE TITLE
Update API based on frontend requirements

### ISSUE THREAD

**Issue by lken274** [se701-group6/A2#59]
**Is your feature request related to a problem? Please describe.**
As the front-end gets more developed, the information required in API calls becomes more clearly understood.

**Describe the type of Document Change you'd like to be added**
Mark with an x
[]: Addition
[x]: Edit
[]: Remove

**Describe the change you would like to be made**
Based on today's front-end work, the API should be slightly updated to include the name of the person who fronted the bill, and other changes being discussed

**Issue Dependencies**
None

**Additional context**
None

**Comment by SeanSpires** [comment]
Sounds good. I'm assigning Daria to this task as well. Daria if there are any updates needed to be done to the API based on changing front-end requirements, leave a comment here.

**Comment by SeanSpires** [comment]
Just to be clear, issue can be closed if need be. Daria can open the issue in the future if API needs to be updated further.

**Comment by williamlixu** [comment]
Had a discussion with @lken274, @tant836, @misl000, @pabloSushibar, @jake-good and refined the API. We just have three basic calls for bills (and payments), to get all bills, create a bill and update payments. The front-end will calculate the params that go into the create a bill payload if we handle different ways of splitting the bill to always send the same payload. The back-end has to process and store this data, then return it the correct format when using the get all bills call. [For more information see the wik](https://github.com/SOFTENG701G1/A1/wiki/API-Description#Bill-endpoints).
