### ISSUE TITLE
Setup Wiki

### ISSUE THREAD

**Issue by williamlixu** [se701-group6/A2#6]
The wiki should provide any additional project documentation needed including a list of contributors (students in the group with their associated GitHub usernames), a list of contributions made by each student, and minutes from any group meetings.

**Comment by skmu104** [comment]
when you mention "a list of contributions made by each student" how do you presume we go about doing this. The meeting minutes page has seperate sections for different groups to document their meetings. Is a seperate page for all individual contributions necessary?

**Comment by SeanSpires** [comment]
Would the "List of contributors" wiki page that would have now be fine for the list of contributions made by each student? And if so can we close this issue?

**Comment by williamlixu** [comment]
Our wiki looks pretty good by now! Looks like it's setup nicely :)
