### ISSUE TITLE
Documentation request: Code Style back-end

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#66]
**Is your feature request related to a problem? Please describe.**
We currently have no documentation on the code style we're currently following/going to follow for the back-end.

**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
We need documentation on the code style currently being used for the back end. Documentation should also include the code style the back-end team is currently using.
 
**Issue Dependencies**
Unsure if this documentation should be done now or after more of the code base has been developed. Leave a comment if you have suggestions.

**Additional context**
n/a

**Comment by williamlixu** [comment]
We have #41 and #58 to cover front-end docs. Working on getting a linter in now :)

**Comment by dder725** [comment]
This one appears to be a bit of a duplicate, as there are some issues related to front-end docs already. Maybe it would be worthwhile to tailor this issue specifically to back-end docs?

**Comment by SeanSpires** [comment]
Agree this issue is a duplicate, will change issue to a documentation request of the coding style used in the back-end.

**Comment by dder725** [comment]
@SeanSpires anyone from back-end wants to pick this issue up? Seems like an important one to finish before the deadline :)

**Comment by SeanSpires** [comment]
I've added the convention that the back-end is following. It's a little brief because pep8(the python convention) is quite all-encompassing.

**Comment by SeanSpires** [comment]
Closing this issue now. If anyone sees room to add more to the code style, reopen the issue, make your changes, and then add a comment on this issue.
