### ISSUE TITLE
Bug report: 'Sign in' title appears on the sign up page

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#68]
**Describe the bug**
When I am on the sign up page, the 'sign in' title appears on top of the input boxes

**To Reproduce**
1. Go to '/#/SignUp'
2. 'Sign in' appears on top of the input boxes

**Severity**
Mark with an x.
[x]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
Nothing appears on top of the input boxes

**Screenshots, Images and Traces**
![signInBug](https://user-images.githubusercontent.com/42598015/76710342-b095f280-676b-11ea-8dd2-552a7ab8062e.png)

**Conditions**
No specific conditions

**Issue Dependencies**
#20 

**Additional context**

**Comment by williamlixu** [comment]
Ah this is because #55 also merged a template for the Sign Up page and the routing but the actual page is yet to be implemented. There's no issue for the Sign Up page yet. I think @tgre605 was going to have a go.

**Comment by dder725** [comment]
@williamlixu  The [issue for sign-up]( https://github.com/SOFTENG701G1/A1/issues/20) was closed as part of #55 due to my misunderstanding of the scope of work that was done in that PR. I shall re-open that issue, my bad. Thank you for the heads up!
