### ISSUE TITLE
Documentation request: Front end testing

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#82]
**Is your feature request related to a problem? Please describe.**
We need documentation on  the approaches we've taken to front-end testing.

**Describe the type of Document Change you'd like to be added**
Mark with an x
[x]: Addition
[]: Edit
[]: Remove

**Describe the change you would like to be made**
Documentation outlining the methods we are using to test the front-end of Split alongside how these methods were developed.

**Issue Dependencies**
n/a

**Additional context**
n/a

**Comment by azizul-i** [comment]
I will handle the documentation for front-end testing 😄

**Comment by Curtiss02** [comment]
I have already written a guide to backend testing using Postman on the wiki. issue #74. If you want me to add any additional stuff let me know,

**Comment by SeanSpires** [comment]
The guide you have Curtiss is perfect, should be fine as of now. Feel free to use Curtiss's wiki as a guideline Azizul.

**Comment by SeanSpires** [comment]
Renaming the issue to Documentation request: Front end testing and unassigning you Curtiss. Let me know if there are any issues with this.

**Comment by azizul-i** [comment]
I have written a guide on Front-end testing; this is now available on the wiki! https://github.com/SOFTENG701G1/A1/wiki/Guide-to-Front-end-Testing

@SeanSpires Could you have a read, and close the issue if it is all good? either wise feel free to let me know if there should be changes/additions to the wiki 😄

**Comment by SeanSpires** [comment]
Looks good, great job! Will close this issue now
