### ISSUE TITLE
Fixing Appendix section in the Wiki Page "Splitting Multiple Bills

### ISSUE THREAD

**Issue by DevashishDhyani** [se701-group6/A2#90]
**Describe the type of Document Change you'd like to be added**
[]: Edit

**Describe the change you would like to be made**
Can one of the documentation leads look into the formatting of the Appendix section in the Wiki page "Splitting Multiple Bills"?

**Comment by skmu104** [comment]
@DevashishDhyani Changes have been made to the appendix, please review and close the issue if satisfactory.

**Comment by DevashishDhyani** [comment]
Looks good to me!
