### ISSUE TITLE
Feature request: Clean up Redux code

### ISSUE THREAD

**Issue by dder725** [se701-group6/A2#91]
**User Story**
As a developer,
I want to remove any remnants of Redux-related code,
So I no longer see obsolete code

**Priority**
[]: High
[]: Medium
[x]: Low

**Describe the solution you want to implement**
Any code related to Redux state management is removed from the sourcecode.

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
n/a

**Comment by williamlixu** [comment]
Closed by #105
